version: 2
updates:
    - package-ecosystem: github-actions
      directory: '/'
      allow:
          - dependency-type: all
      schedule:
          interval: weekly
      pull-request-branch-name:
          separator: '-'
    - package-ecosystem: composer
      directory: '/'
      versioning-strategy: widen
      allow:
          - dependency-type: all
      schedule:
          interval: weekly
      pull-request-branch-name:
          separator: '-'
